name: app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

# Dependencies - - - - - - - - - - - - - - - - - - - - - - - - - - - -
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.1.0
  flutter_svg: ^1.1.1+1
  sqflite: ^2.0.3
  path_provider: ^2.0.11
  path: ^1.8.2
  google_fonts: ^3.0.1
  flutter_bloc: ^8.0.1
  date_picker_timeline: ^1.2.3
  syncfusion_flutter_calendar: ^19.4.54
  flutter_local_notifications: ^9.2.0
  intl: ^0.17.0
  timezone: ^0.8.0
  rxdart: ^0.27.4
  flutter_native_timezone: ^1.0.10
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
